#!/usr/bin/env python3
"""
Database layer for the Layer Vote Bot.

Uses SQLite with tables:
- guild_settings: per-guild configuration
- layer_cache: cached layer data from layers.json
- events: per-channel suggestion/voting cycles
- voting_history: past winning layers

Every public function accepts a guild_id to ensure full multi-guild isolation.
"""

import json
import os
import sqlite3
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger("layer_vote.db")

DB_FILE = os.path.join("data", "layer_vote.db")

# ---------------------------------------------------------------------------
# JSON helpers for datetime round-tripping
# ---------------------------------------------------------------------------

class _DateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return {"__datetime__": obj.isoformat()}
        return super().default(obj)


def _datetime_hook(obj):
    if "__datetime__" in obj:
        return datetime.fromisoformat(obj["__datetime__"])
    return obj


def _dumps(obj) -> str:
    return json.dumps(obj, cls=_DateTimeEncoder)


def _loads(raw: str):
    return json.loads(raw, object_hook=_datetime_hook)


# ---------------------------------------------------------------------------
# Default guild settings
# ---------------------------------------------------------------------------

DEFAULT_GUILD_SETTINGS = {
    "organizer_role_id": 0,
    "log_channel_id": None,
    "language": "en",
    "allowed_gamemodes": ["AAS", "RAAS", "Invasion", "TerritoryControl", "Destruction", "Insurgency"],
    "blacklisted_maps": [],
    "blacklisted_factions": [],
    "blacklisted_units": [],
    "max_suggestions_per_user": 2,
    "max_total_suggestions": 25,
    "history_lookback_events": 3,
    # How many times a user may remove their own suggestion per event. 0
    # disables the user-facing "Remove Suggestion" button entirely.
    "max_self_removals_per_user": 1,
    # Per-guild default of which layer sources are offered to users when
    # creating a suggestion event. Empty list = all configured sources allowed.
    "allowed_sources": [],
    # Defaults used by /create_layer_suggestion when the corresponding
    # parameter is omitted. suggestion_start/duration are stored as duration
    # strings (e.g. "1h", "30m"); start is applied as an offset from now.
    "default_suggestion_start": None,
    "default_suggestion_duration": None,
    "default_voting_duration_hours": 24,
    "default_allow_multiple_votes": False,
}


# ---------------------------------------------------------------------------
# Schema initialisation
# ---------------------------------------------------------------------------

def _get_conn() -> sqlite3.Connection:
    os.makedirs(os.path.dirname(DB_FILE), exist_ok=True)
    conn = sqlite3.connect(DB_FILE)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _migrate_layer_cache_for_source(conn: sqlite3.Connection):
    """Drop & recreate layer_cache if it predates the `source` column.

    The cache is fully regenerated by fetch_and_cache_layers() on next refresh,
    so dropping is safe — far simpler than an in-place ALTER + UNIQUE rebuild.
    """
    cur = conn.execute("PRAGMA table_info(layer_cache)")
    cols = [row[1] for row in cur.fetchall()]
    if not cols:
        return  # table doesn't exist yet; CREATE TABLE below will make it
    if "source" not in cols:
        logger.info("Migrating layer_cache: adding `source` column (cache will rebuild on next refresh)")
        conn.execute("DROP TABLE layer_cache")


def init_db():
    """Create tables if they don't exist."""
    conn = _get_conn()
    _migrate_layer_cache_for_source(conn)
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS guild_settings (
            guild_id     INTEGER PRIMARY KEY,
            settings     TEXT    NOT NULL,
            created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
            updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
        );

        CREATE TABLE IF NOT EXISTS layer_cache (
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            raw_name                TEXT    NOT NULL,
            source                  TEXT    NOT NULL DEFAULT 'default',
            map_name                TEXT    NOT NULL,
            map_id                  TEXT    NOT NULL,
            gamemode                TEXT    NOT NULL,
            layer_version           TEXT,
            map_size_km             REAL,
            factions_json           TEXT    NOT NULL DEFAULT '[]',
            team1_allowed_alliances TEXT    NOT NULL DEFAULT '[]',
            team2_allowed_alliances TEXT    NOT NULL DEFAULT '[]',
            cached_at               TEXT    NOT NULL DEFAULT (datetime('now')),
            UNIQUE(raw_name, source)
        );

        CREATE INDEX IF NOT EXISTS idx_layer_cache_map
            ON layer_cache(map_name, gamemode);
        CREATE INDEX IF NOT EXISTS idx_layer_cache_source
            ON layer_cache(source);

        CREATE TABLE IF NOT EXISTS events (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id     INTEGER NOT NULL,
            channel_id   INTEGER NOT NULL,
            event_data   TEXT    NOT NULL,
            status       TEXT    NOT NULL DEFAULT 'active',
            created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
            updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
        );

        CREATE INDEX IF NOT EXISTS idx_events_guild
            ON events(guild_id, status);
        CREATE INDEX IF NOT EXISTS idx_events_channel
            ON events(guild_id, channel_id, status);

        CREATE TABLE IF NOT EXISTS voting_history (
            id               INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id         INTEGER NOT NULL,
            channel_id       INTEGER NOT NULL,
            all_suggestions  TEXT    NOT NULL DEFAULT '[]',
            winning_layer    TEXT,
            completed_at     TEXT    NOT NULL DEFAULT (datetime('now'))
        );

        CREATE INDEX IF NOT EXISTS idx_history_guild
            ON voting_history(guild_id, channel_id, completed_at);
    """)
    conn.commit()
    conn.close()
    logger.info(f"Database initialised: {DB_FILE}")


# ---------------------------------------------------------------------------
# Guild settings
# ---------------------------------------------------------------------------

def get_guild_settings(guild_id: int) -> Optional[dict]:
    """Return settings dict for a guild, or None if not configured."""
    conn = _get_conn()
    row = conn.execute(
        "SELECT settings FROM guild_settings WHERE guild_id = ?", (guild_id,)
    ).fetchone()
    conn.close()
    if row is None:
        return None
    settings = _loads(row[0])
    merged = {**DEFAULT_GUILD_SETTINGS, **settings}
    return merged


def save_guild_settings(guild_id: int, settings: dict):
    """Upsert guild settings."""
    conn = _get_conn()
    with conn:
        conn.execute(
            """INSERT INTO guild_settings (guild_id, settings, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(guild_id) DO UPDATE SET settings=excluded.settings, updated_at=excluded.updated_at""",
            (guild_id, _dumps(settings)),
        )
    conn.close()


def get_guild_language(guild_id: int) -> str:
    """Shortcut: return language code for a guild."""
    settings = get_guild_settings(guild_id)
    if settings is None:
        return DEFAULT_GUILD_SETTINGS["language"]
    return settings.get("language", DEFAULT_GUILD_SETTINGS["language"])


def guild_is_configured(guild_id: int) -> bool:
    """Check if a guild has run /setup."""
    return get_guild_settings(guild_id) is not None


# ---------------------------------------------------------------------------
# Layer cache
# ---------------------------------------------------------------------------

def clear_layer_cache():
    """Delete all cached layers."""
    conn = _get_conn()
    with conn:
        conn.execute("DELETE FROM layer_cache")
    conn.close()


def _source_filter(allowed_sources: Optional[list[str]], prefix: str = " AND ") -> tuple[str, list]:
    """Build an SQL fragment + params for filtering by source.

    Returns ("", []) when no filter should be applied (None or empty list).
    Otherwise returns (f"{prefix}source IN (?,?,...)", [src1, src2, ...]).
    """
    if not allowed_sources:
        return "", []
    placeholders = ",".join("?" * len(allowed_sources))
    return f"{prefix}source IN ({placeholders})", list(allowed_sources)


def upsert_layer(raw_name: str, source: str, map_name: str, map_id: str, gamemode: str,
                 layer_version: Optional[str], factions: list,
                 team1_alliances: list, team2_alliances: list,
                 map_size_km: Optional[float] = None):
    """Insert or update a single layer in the cache.

    Layers are uniquely identified by (raw_name, source) — the same rawName
    may legitimately appear in multiple sources.
    """
    conn = _get_conn()
    with conn:
        conn.execute(
            """INSERT INTO layer_cache
               (raw_name, source, map_name, map_id, gamemode, layer_version,
                map_size_km, factions_json, team1_allowed_alliances,
                team2_allowed_alliances, cached_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
               ON CONFLICT(raw_name, source) DO UPDATE SET
                 map_name=excluded.map_name, map_id=excluded.map_id,
                 gamemode=excluded.gamemode, layer_version=excluded.layer_version,
                 map_size_km=excluded.map_size_km,
                 factions_json=excluded.factions_json,
                 team1_allowed_alliances=excluded.team1_allowed_alliances,
                 team2_allowed_alliances=excluded.team2_allowed_alliances,
                 cached_at=excluded.cached_at""",
            (raw_name, source, map_name, map_id, gamemode, layer_version,
             map_size_km, json.dumps(factions),
             json.dumps(team1_alliances), json.dumps(team2_alliances)),
        )
    conn.close()


def get_layer_cache_count() -> int:
    """Return number of cached layers."""
    conn = _get_conn()
    row = conn.execute("SELECT COUNT(*) FROM layer_cache").fetchone()
    conn.close()
    return row[0] if row else 0


def get_unique_maps(excluded_maps: list[str] = None,
                    allowed_sources: Optional[list[str]] = None) -> list[str]:
    """Return sorted list of unique map names, optionally excluding some.

    `allowed_sources` filters the underlying layer_cache rows to those tagged
    with one of the given source names. None or empty list = no source filter.
    """
    where, params = _source_filter(allowed_sources, prefix=" WHERE ")
    sql = f"SELECT DISTINCT map_name FROM layer_cache{where} ORDER BY map_name"
    conn = _get_conn()
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    maps = [r[0] for r in rows]
    if excluded_maps:
        maps = [m for m in maps if not any(m.lower().startswith(e.lower()) for e in excluded_maps)]
    return maps


def get_modes_for_map(map_name: str, allowed_gamemodes: list[str] = None,
                      allowed_sources: Optional[list[str]] = None) -> list[dict]:
    """Return available mode+version combos for a map.

    Returns list of dicts with keys: gamemode, layer_version, raw_name, source, display.
    `allowed_sources` filters layers to those whose source is in the list.
    """
    src_clause, src_params = _source_filter(allowed_sources)
    sql = (
        f"SELECT gamemode, layer_version, raw_name, source FROM layer_cache "
        f"WHERE map_name = ?{src_clause} ORDER BY gamemode, layer_version"
    )
    conn = _get_conn()
    rows = conn.execute(sql, [map_name, *src_params]).fetchall()
    conn.close()

    results = []
    for gamemode, version, raw_name, source in rows:
        if allowed_gamemodes and gamemode not in allowed_gamemodes:
            continue
        display = gamemode
        if version:
            display = f"{gamemode} {version}"
        results.append({
            "gamemode": gamemode,
            "layer_version": version,
            "raw_name": raw_name,
            "source": source,
            "display": display,
        })
    return results


def get_layer_by_raw_name(raw_name: str,
                          allowed_sources: Optional[list[str]] = None) -> Optional[dict]:
    """Return full layer data by raw_name.

    `allowed_sources` filters to layers whose source is in the list. When the
    same raw_name exists in multiple matching sources, the first row found wins.
    """
    src_clause, src_params = _source_filter(allowed_sources)
    sql = (
        "SELECT raw_name, source, map_name, map_id, gamemode, layer_version, "
        "factions_json, team1_allowed_alliances, team2_allowed_alliances "
        f"FROM layer_cache WHERE raw_name = ?{src_clause} LIMIT 1"
    )
    conn = _get_conn()
    row = conn.execute(sql, [raw_name, *src_params]).fetchone()
    conn.close()
    if row is None:
        return None
    return {
        "raw_name": row[0],
        "source": row[1],
        "map_name": row[2],
        "map_id": row[3],
        "gamemode": row[4],
        "layer_version": row[5],
        "factions": json.loads(row[6]),
        "team1_allowed_alliances": json.loads(row[7]),
        "team2_allowed_alliances": json.loads(row[8]),
    }


def get_unique_factions(allowed_sources: Optional[list[str]] = None) -> list[str]:
    """Return sorted list of all unique faction IDs from cached layers."""
    where, params = _source_filter(allowed_sources, prefix=" WHERE ")
    sql = f"SELECT factions_json FROM layer_cache{where}"
    conn = _get_conn()
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    factions = set()
    for (fj,) in rows:
        for f in json.loads(fj):
            if isinstance(f, dict) and "factionId" in f:
                factions.add(f["factionId"])
            elif isinstance(f, str):
                factions.add(f)
    return sorted(factions)


def get_unique_unit_types(allowed_sources: Optional[list[str]] = None) -> list[str]:
    """Return sorted list of all unique unit type names from cached layers."""
    where, params = _source_filter(allowed_sources, prefix=" WHERE ")
    sql = f"SELECT factions_json FROM layer_cache{where}"
    conn = _get_conn()
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    units = set()
    for (fj,) in rows:
        for f in json.loads(fj):
            if isinstance(f, dict):
                for ut in f.get("unitTypes", []):
                    if isinstance(ut, dict):
                        units.add(ut.get("type", ""))
                    elif isinstance(ut, str):
                        units.add(ut)
    units.discard("")
    return sorted(units)


def get_unique_gamemodes(allowed_sources: Optional[list[str]] = None) -> list[str]:
    """Return sorted list of all unique gamemodes from cached layers."""
    where, params = _source_filter(allowed_sources, prefix=" WHERE ")
    sql = f"SELECT DISTINCT gamemode FROM layer_cache{where} ORDER BY gamemode"
    conn = _get_conn()
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    return [r[0] for r in rows]


def get_map_sizes(allowed_sources: Optional[list[str]] = None) -> "dict[str, float]":
    """Return {map_name: max_layer_size_km} from the cache.

    A map's canonical size is taken as the largest size among its layers, since
    skirmish/seed sub-layers reuse the same mapId with a smaller playable area.
    Maps with no usable size data (all NULL) are omitted.
    """
    where, params = _source_filter(allowed_sources, prefix=" WHERE ")
    where = (where + " AND " if where else " WHERE ") + "map_size_km IS NOT NULL"
    sql = f"SELECT map_name, MAX(map_size_km) FROM layer_cache{where} GROUP BY map_name"
    conn = _get_conn()
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    return {name: size for name, size in rows if size is not None}


def get_unique_sources() -> list[str]:
    """Return sorted list of distinct source names currently in the cache."""
    conn = _get_conn()
    rows = conn.execute(
        "SELECT DISTINCT source FROM layer_cache ORDER BY source"
    ).fetchall()
    conn.close()
    return [r[0] for r in rows]


# ---------------------------------------------------------------------------
# Events — one active event per (guild, channel)
# ---------------------------------------------------------------------------

def get_active_event_unsafe(db_id: int) -> Optional[dict]:
    """Return an active event by db_id without a guild filter.

    Reserved for trusted internal callers (background tasks, debounced
    refreshes) where the db_id is already known to belong to this bot.
    Public-interaction code paths must use get_event_by_db_id, which enforces
    guild_id as a security boundary.
    """
    conn = _get_conn()
    row = conn.execute(
        "SELECT id, guild_id, channel_id, event_data FROM events WHERE id = ? AND status = 'active'",
        (db_id,),
    ).fetchone()
    conn.close()
    if row is None:
        return None
    return {
        "db_id": row[0],
        "guild_id": row[1],
        "channel_id": row[2],
        "event": _loads(row[3]),
    }


def get_event_by_db_id(guild_id: int, db_id: int) -> Optional[dict]:
    """Return a specific active event by its DB row id, or None.

    guild_id is enforced as a security boundary so cross-guild button
    interactions can't load each other's events.
    """
    conn = _get_conn()
    row = conn.execute(
        """SELECT id, event_data, channel_id
           FROM events
           WHERE id = ? AND guild_id = ? AND status = 'active'
           LIMIT 1""",
        (db_id, guild_id),
    ).fetchone()
    conn.close()
    if row is None:
        return None
    return {"db_id": row[0], "event": _loads(row[1]), "channel_id": row[2]}


def get_active_events_in_channel(guild_id: int, channel_id: int) -> list[dict]:
    """Return all active events in a channel (multiple are allowed)."""
    conn = _get_conn()
    rows = conn.execute(
        """SELECT id, event_data
           FROM events
           WHERE guild_id = ? AND channel_id = ? AND status = 'active'
           ORDER BY id""",
        (guild_id, channel_id),
    ).fetchall()
    conn.close()
    return [{"db_id": row[0], "event": _loads(row[1]), "channel_id": channel_id}
            for row in rows]


def get_all_active_events_global() -> list[dict]:
    """Return all active events across all guilds (for background tasks)."""
    conn = _get_conn()
    rows = conn.execute(
        """SELECT id, guild_id, channel_id, event_data
           FROM events WHERE status = 'active'"""
    ).fetchall()
    conn.close()
    return [
        {
            "db_id": row[0],
            "guild_id": row[1],
            "channel_id": row[2],
            "event": _loads(row[3]),
        }
        for row in rows
    ]


def save_event(db_id: int, event_data: dict):
    """Update an existing event row."""
    conn = _get_conn()
    with conn:
        conn.execute(
            """UPDATE events
               SET event_data = ?, updated_at = datetime('now')
               WHERE id = ?""",
            (_dumps(event_data), db_id),
        )
    conn.close()


def create_event(guild_id: int, channel_id: int, event_data: dict) -> int:
    """Insert a new active event. Returns the new row id."""
    conn = _get_conn()
    with conn:
        cur = conn.execute(
            """INSERT INTO events (guild_id, channel_id, event_data, status)
               VALUES (?, ?, ?, 'active')""",
            (guild_id, channel_id, _dumps(event_data)),
        )
        new_id = cur.lastrowid
    conn.close()
    logger.info(f"Event created: db_id={new_id}, guild={guild_id}, channel={channel_id}")
    return new_id


def complete_event(db_id: int):
    """Mark an event as completed (soft-delete)."""
    conn = _get_conn()
    with conn:
        conn.execute(
            "UPDATE events SET status = 'completed_' || id, updated_at = datetime('now') WHERE id = ?",
            (db_id,),
        )
    conn.close()
    logger.info(f"Event completed: db_id={db_id}")


def delete_event(db_id: int):
    """Mark an event as deleted (soft-delete)."""
    conn = _get_conn()
    with conn:
        conn.execute(
            "UPDATE events SET status = 'deleted_' || id, updated_at = datetime('now') WHERE id = ?",
            (db_id,),
        )
    conn.close()
    logger.info(f"Event deleted: db_id={db_id}")




# ---------------------------------------------------------------------------
# Voting history
# ---------------------------------------------------------------------------

def save_voting_history(guild_id: int, channel_id: int, all_suggestions: list,
                        winning_layer: Optional[dict]):
    """Save completed event to voting history."""
    conn = _get_conn()
    with conn:
        conn.execute(
            """INSERT INTO voting_history (guild_id, channel_id, all_suggestions, winning_layer)
               VALUES (?, ?, ?, ?)""",
            (guild_id, channel_id, _dumps(all_suggestions),
             _dumps(winning_layer) if winning_layer else None),
        )
    conn.close()


def get_recent_history(guild_id: int, channel_id: int, limit: int = 10) -> list[dict]:
    """Return recent voting history entries."""
    conn = _get_conn()
    rows = conn.execute(
        """SELECT id, all_suggestions, winning_layer, completed_at
           FROM voting_history
           WHERE guild_id = ? AND channel_id = ?
           ORDER BY completed_at DESC LIMIT ?""",
        (guild_id, channel_id, limit),
    ).fetchall()
    conn.close()
    return [
        {
            "id": row[0],
            "all_suggestions": _loads(row[1]),
            "winning_layer": _loads(row[2]) if row[2] else None,
            "completed_at": row[3],
        }
        for row in rows
    ]


def delete_voting_history_entry(entry_id: int) -> bool:
    """Delete a single voting_history row. Returns True if a row was removed."""
    conn = _get_conn()
    with conn:
        cur = conn.execute("DELETE FROM voting_history WHERE id = ?", (entry_id,))
        removed = cur.rowcount > 0
    conn.close()
    if removed:
        logger.info(f"Voting history entry deleted: id={entry_id}")
    return removed


def get_blocked_suggestions(guild_id: int, channel_id: int, lookback: int) -> list[dict]:
    """Return all suggestions from the last `lookback` events for blocking.

    Includes both the full list of suggestions made during each event AND the
    recorded winning_layer, so that manual history entries that only carry a
    winner still get blocked.
    """
    history = get_recent_history(guild_id, channel_id, limit=lookback)
    blocked = []
    for entry in history:
        for suggestion in entry.get("all_suggestions", []):
            blocked.append(suggestion)
        winner = entry.get("winning_layer")
        if winner:
            blocked.append(winner)
    return blocked


# Guild-settings keys that get snapshotted into event["config"] at creation
# time. After Phase 2, every layer suggestion event carries its own copy of
# these values so admins can edit them per-event via the DM edit dialog
# without affecting other events or the guild defaults.
EVENT_CONFIG_KEYS: tuple[str, ...] = (
    "allowed_gamemodes",
    "blacklisted_maps",
    "blacklisted_factions",
    "blacklisted_units",
    "max_suggestions_per_user",
    "max_total_suggestions",
    "history_lookback_events",
    "max_self_removals_per_user",
)


def _snapshot_event_config(settings: Optional[dict]) -> dict:
    """Build the per-event config dict from a guild settings dict."""
    src = settings or DEFAULT_GUILD_SETTINGS
    snapshot: dict = {}
    for key in EVENT_CONFIG_KEYS:
        value = src.get(key, DEFAULT_GUILD_SETTINGS.get(key))
        # Defensive copy for mutable types so later edits don't bleed into
        # the guild settings dict.
        if isinstance(value, list):
            snapshot[key] = list(value)
        elif isinstance(value, dict):
            snapshot[key] = dict(value)
        else:
            snapshot[key] = value
    return snapshot


def build_default_event(suggestion_start_time=None,
                        settings: Optional[dict] = None,
                        event_name: Optional[str] = None) -> dict:
    """Build a fresh event data dict.

    `settings` is the guild settings dict at creation time; the event
    captures a snapshot of the relevant keys (see EVENT_CONFIG_KEYS) so
    each event has its own independently-editable configuration.

    `event_name` is an optional human-readable label. None / empty means
    "use the `Event #{db_id}` fallback at display time".
    """
    return {
        "phase": "created",
        "event_name": event_name,
        "event_message_id": None,
        "suggestion_start_time": suggestion_start_time,
        "suggestion_end_time": None,
        "suggestion_duration_seconds": None,
        "voting_start_time": None,
        "voting_duration_hours": 24,
        "poll_message_id": None,
        "max_voting_layers": 10,
        "selected_for_vote": [],
        "winning_layer": None,
        "allow_multiple_votes": False,
        "suggestions": [],
        # Per-user count of how many of their own suggestions a user has
        # removed via the "Remove Suggestion" button (str(user_id) -> int).
        # Capped per event by config["max_self_removals_per_user"].
        "user_removal_counts": {},
        # Empty list = all configured sources allowed for this event. Set by
        # the admin at /create_layer_suggestion time (defaults to the guild's
        # allowed_sources setting).
        "allowed_sources": [],
        # Per-event participation gate. Both empty = anyone can suggest/vote
        # (current behavior). When non-empty, only matching members may use
        # Suggest Layer or join the private voting thread.
        "allowed_role_ids": [],
        "allowed_user_ids": [],
        # Set when /start_vote creates a private thread for a gated event
        # (None for unrestricted events that vote in the parent channel).
        "vote_thread_id": None,
        # Per-event snapshot of guild settings that influence the suggestion
        # flow. Edited via the Admin → Edit DM dialog without affecting other
        # events. Readers should call _event_settings(event, guild_settings)
        # in bot.py to merge this with guild fallbacks.
        "config": _snapshot_event_config(settings),
    }
